### ISSUE TITLE
webrtc assert (and more)

### ISSUE THREAD

**Issue by anchor76** [ValveSoftware/GameNetworkingSockets#146]
i working with the latest (1.2.0) release, i have two peers. **peer-a** and **peer-b**.

- **peer-a** trying to connect to **peer-b** with _ConnectP2PCustomSignaling()_
- the webrtc ip lookup process running and ending fine on **peer-a** side.
- the peer-data transmitted successfully to **peer-b**
- **peer-b** starting the webrtc ip lookup process, and asserting in a webrtc function call:

file: p2p_transport_channel.cc
function: P2PTransportChannel::writable()
line: RTC_DCHECK_RUN_ON(network_thread_);
this thread check fails.

any advice?

(our project is huge, but  i can make a tiny sample project to show the problem)

side note:
-----------
i tried to check the head, now it compiles fine on windows (thanks for the fix)
but it fails upon the first _ConnectByIPAddress()_ function call.
it's an assert_cast<>. 
file: steamnetworkingsockets_udp.h
class: CSteamNetworkConnectionUDP
function: Transport()
the assert_cast<> fails :+1: i tried the static lib, and the dll too, same result.

im really stuck with the p2p feature now ... any help would be appreciated.

edit: platform: windows x64

**Comment by LeventSevgili** [comment]
Hey,

I think i had the same problem, i commented it out for now and rebuilt. It is the static and dynamic assertion cast equation check for Debug build i guess. It is static cast for Release. You are having it on Debug build right?

**Comment by anchor76** [comment]
hello @LeventSevgili , thanks for your response.
yes it's debug build, and windows x64 with vs2019.
i'll try to remove it, but an assert indicating an abnormal state, it should be checked by the authors too.

the other assert (RTC_DCHECK_RUN_ON in webrtc) also exist only in debug mode.

**Comment by LeventSevgili** [comment]
Well it seems it is updated but sorry still i got assertion error when i run the test_p2p.exe as a client. (server is running). No assertion at server test_p2p.exe but an assert error occurs at client test_p2p.exe.

I just pulled the latest and generated the projects and sln with CMake from scratch for my windows 10 VS 2019 system.

```
C:\Users\loren\Desktop\Source\GameNetworkingSockets\bin\bin\Debug>test_p2p.exe --client --identity-local str:levent --identity-remote str:identity1
  0.001517 Initialized low level socket/threading support.
  0.002991 Connecting to 'str:identity1', virtual port 0, from local virtual port 0.
  0.003076 Creating signaling session for peer 'str:identity1'
  1.255520 C:\Users\loren\Desktop\Source\GameNetworkingSockets\src\steamnetworkingsockets\clientlib\steamnetworkingsockets_lowlevel.cpp(1151): SDR service thread gave up on lock after waiting 250ms.  This directly adds to delay of processing of network packets!
Assertion failed: !"TEST FAILED", file C:\Users\loren\Desktop\Source\GameNetworkingSockets\tests\test_common.cpp, line 46
```

But when i comment out the "DbgAssert..." line 152 from "dbg.h" as below to test, it works. It can now connect to the server via signal server.

```
template<typename DEST_POINTER_TYPE, typename SOURCE_POINTER_TYPE>
inline DEST_POINTER_TYPE assert_cast(SOURCE_POINTER_TYPE* pSource)
{
    //DbgAssert( static_cast<DEST_POINTER_TYPE>(pSource) == dynamic_cast<DEST_POINTER_TYPE>(pSource) );
    return static_cast<DEST_POINTER_TYPE>(pSource);
}
```
I also noticed the "Enable RTTI in _DEBUG for assert_cast" commit fix on CMakeLists.txt.
It adds below lines. 

```
      # Disable RTTI.  Escept in debug, because we use it in assert_cast
                if(NOT CMAKE_BUILD_TYPE STREQUAL Debug)
                    target_compile_options(${TGT} PRIVATE /GR- )
                endif()
```
Maybe it would be better to have the else section of if statement to set RTTI as /GR, because it assumes the default setting is /GR for RTTI. I think this way because when i configure and generated the projects and sln with CMake from scratch, i still has /GR- for RTTI on Debug Configuration on Visual Studio property page for GameNetworkingSockets Project. That's just a thought of course. Thank you !!

I also tested when RTTI is on with /GR on Debug, the fix is working! Just fyi.
