### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by yamashi** [ValveSoftware/GameNetworkingSockets#164]
Hello,

While working on the userdata PR, I found that the code base is a bit complicated to work with because it's a bit obscure and files are a quite large containing multiple classes etc. Is that intended or is this a symptom of on going lack of time to refactor? The code also contains many singletons, removing them would help make the code more modular.

I don't mind giving a hand with this is something you want. 
The code could also benefit from some modernization (removing the new calls for example), maybe upgrade the C++ toolchain to C++14/17/20?

Let me know what you think.

Best,
Max

**Comment by fletcherdvalve** [comment]
Did you see this bit of the readme?

The desire to match the Steamworks SDK also explains a somewhat anachronistic coding style and weird directory layout. This project is kept in sync with the Steam code here at Valve. When we extracted the code from the much larger codebase, we had to do some relatively gross hackery. The files in folders named tier0, tier1, vstdlib, common, etc have especially suffered trauma. Also if you see code that appears to have unnecessary layers of abstraction, it's probably because those layers are needed to support relayed connection types or some part of the Steamworks SDK.
