### ISSUE TITLE
SteamNetworkingIPAddr::ParseString(char const*) is not defined in release

### ISSUE THREAD

**Issue by Ravbug** [ValveSoftware/GameNetworkingSockets#171]
When static linking, `SteamNetworkingIPAddr::ParseString(char const*)` is not defined in Release, but is defined in every other CMake configuration (checked, profile, debug).

This issue affects the latest commit on Linux (gcc), macOS / iOS (Apple Clang) but not Windows (MSVC). 

I am using it like this:
```cpp
SteamNetworkingIPAddr ip;
ip.Clear();
if(!ip.ParseString(address.c_str())){
    Debug::Fatal("Invalid IP: {}",address);
}
ip.m_port = port;
```

In `steamnetworkingtypes.h` in release, the compiler warns that it is not defined:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/22283943/110866316-d324f380-8279-11eb-8d53-6ff8cd0f9f29.png">

**Comment by fletcherdvalve** [comment]
OK, so this is admittedly weird, but have you tried including isteamnetworkingutils.h in the file where that is called?  That function is intended to really be inline (because the actual implementation varies depending on the build environment, and also we strive to only export plain C symbols from the library).  But I wanted to keep steamnetworkingtypes as slim as possible and not become a dependency nexus and kill compiled times.  So, this is kind of weird, I know, but this is the workaround.

**Comment by Ravbug** [comment]
This fixes it, thanks.
