### ISSUE TITLE
Contact information missing

### ISSUE THREAD

**Issue by samyatchmenoff** [ValveSoftware/GameNetworkingSockets#187]
The README mentions contacting for console code, but does not indicate how or who to contact.

**Comment by seamanm** [comment]
up,I want to know about compiling and using on Android

**Comment by fletcherdvalve** [comment]
I apologize on not fixing this.  And if you have filed a Steam support ticket with a similar question, and I haven't responded....I also apologize.

An update:

For consoles and people who want SDR support: We have been working through some issues internally and with the platform holders about the best way to distribute this.  I'm hopeful that we'll have some good answers soon!

For android: If you don't need SDR, then you can use the opensource code.  The missing piece is getting cmake to play nice.  If you know about how to do that and want to contribute, I would welcome the help.  (See #102)

**Comment by zpostfacto** [comment]
I've updated the readme to just direct people to the steamworks documentation, and there we basically say to file a support ticket.  We've run into a bunch of practical problems giving access to this code.  If it's just plain old UDP, it's probably not a huge deal, we don't mind giving access to platform stuff approved developers.  We'd totally opensource all of that if it were up to us.  I am working on better organizing the source code into separate chunks that can be distributed separately to only those who should get access.  But giving people source code to talk to the live services that we have to support (especially SDR) is really tricky because we then are committing to support in perpetuity tons of different old versions of the code, which will obviously have bugs or security vulns, or speak an old version of the protocol, and we do not have the ability to update that code but we have to support it.  Devs disappear or cannot or will not update their game, and then if we drop support for those old games, we are the bad guys.  So we have decided for now that we can only offer this to partners with whom we have a strong ongoing relationship and can trust to update the software if we ask them to.

As for android, I still need help with cmake.

So I don't think there's anything to track in this bug.
