### ISSUE TITLE
How to use ISteamNetworkingMessages?

### ISSUE THREAD

**Issue by djdron** [ValveSoftware/GameNetworkingSockets#200]
Hello!)

I'm trying to use ISteamNetworkingMessages to communicate steam game version with non-steam game version.
I've built GameNetworkingSockets, linked it to project and got error LNK2019: unresolved external symbol __imp_SteamNetworkingMessages_LibV2 referenced in function "foo".
I haven't found where is ISteamNetworkingMessages implementation created.
One place is inside CSteamNetworkingSockets::GetSteamNetworkingMessages(), but I'm not using SteamNetworkingSockets, only SteamNetworkingMessages.

Is it possible now? Can i just add SteamNetworkingMessages_LibV2 function with new CSteamNetworkingMessages(), or it's much harder to do?

**Comment by djdron** [comment]
I've added
```
STEAMNETWORKINGSOCKETS_INTERFACE ISteamNetworkingMessages* SteamNetworkingMessages_LibV2()
{
	return s_pSteamNetworkingSockets->GetSteamNetworkingMessages();
}

```
Hacking...

**Comment by fletcherdvalve** [comment]
Thanks for this.

I would add a NULL, check, so something like this:

```
STEAMNETWORKINGSOCKETS_INTERFACE ISteamNetworkingMessages *SteamNetworkingMessages_LibV2()
{
	if ( !s_pSteamNetworkingSockets )
		return nullptr;
	return s_pSteamNetworkingSockets->GetSteamNetworkingMessages();
}
```

Feel free to submit a PR with this fix.

HOWEVER one question -- how is the opensource code going to send rendezvous signals with the Steam version?

**Comment by djdron** [comment]
> Feel free to submit a PR with this fix.

Ok, I've created PR #201.

> HOWEVER one question -- how is the opensource code going to send rendezvous signals with the Steam version?

I don't know yet.. Is it possible at all?
I thought to use GameNetworkingSockets library instead of Steam SDK version for both game versions (steam and non-steam).
But in latest Steam SDK 1.52 we have "SteamNetworkingSockets009" version, and in GameNetworkingSockets v1.3 we have "SteamNetworkingSockets_LibV9".
Are they same and compatible ?
I need to try...

**Comment by fletcherdvalve** [comment]
You'll need some way to send rendezvous messages (often called "signaling") through a trusted third party between the peers, for them to negotiate a P2P connection.  Because they will not initially know their IP addresses, etc.  There is a mechanism in gamenetworkingsockets to use a custom signaling service, so it's possible, but it is something that you will need to supply.  Between two players on Steam, those RSVP messages go through the Steam backend.

Also, how will you identify the non-Steam peers?  They need some sort of identity, and you'll need a trusted central authority to manage that.

**Comment by djdron** [comment]
@fletcherdvalve 
I've implemented rendezvous messages, assigned my custom identities and got connected after some fixes (look PR #207).

**Comment by fletcherdvalve** [comment]
Nice!  So you are communicating between the Steam and non-Steam version of the game, using a custom signaling backend?  That's great!  Can you tell me a bit more about how your solution works?  Did you tell the Steam client to use the custom signaling mechanism globally?

I saw your PR.  I might need to tweak the check so that it allows your case in but still traps invalid use cases earlier.  I think right now any invalid identities would get a bit too far into the system and lead to confusing error messages and behaviour, which I want to avoid.

**Comment by djdron** [comment]
> Can you tell me a bit more about how your solution works? Did you tell the Steam client to use the custom signaling mechanism globally?

My solution works via [enet](http://enet.bespin.org/) transport - all clients (steam and non-steam) connected to rendezvous server and report their custom id's (set by SetGenericBytes).

> I saw your PR. I might need to tweak the check so that it allows your case in but still traps invalid use cases earlier. I think right now any invalid identities would get a bit too far into the system and lead to confusing error messages and behaviour, which I want to avoid.

What do you mean by "invalid identities"?
