### ISSUE TITLE
Any way to not accept incoming connection based on custom info coming from the client?

### ISSUE THREAD

**Issue by Zylann** [ValveSoftware/GameNetworkingSockets#213]
I'm wondering if the library has any means for me to write something like this:

```
// Pseudocode
// On the server, this gets called when there is an incoming connection:
void OnConnecting(Connection connection, ConnectionInfo data)
{
    if(data.clientVersion != CURRENT_VERSION)
    {
        DenyConnection()
    }
    else
    {
        AcceptConnection()
    }
}
```

Inside the callback where I decide what to do with the incoming connection (`SteamNetConnectionStatusChangedCallback_t` I assume), I have no idea how I'm supposed to get what version of the game the connecting client is using.
I see connections can have userData attached, but I suspect this is not really what I'm looking for?

To clarify, if possible, I wish to do this without having to first accept the connection, because it sounds like it is the job of such callback? (and also would be simpler to handle than having to define a custom state and custom messages to exchange before the game can consider the client as connected)

**Comment by fletcherdvalve** [comment]
There's no mechanism to send a blob of data and have it be available for the initial connect.  This would definitely be a useful feature!  I have thought about adding it, but it's not high enough priority yet.

So you'll need to do exactly what you would need to do with TCP, which is accept the connection. and then send the initial client data in a regular (probably reliable) message.  Note that it is allowed for the client to queue messages before its connection is accepted, so that could simplify your client state machine at least.  But the server state machine will have to deal with all this.

And you are right, "user data" is not the droid you are looking for.  That is not communicated between peers, it is strictly a local thing.
