### ISSUE TITLE
Sodium crash in crypto handshake

### ISSUE THREAD

**Issue by yamashi** [ValveSoftware/GameNetworkingSockets#243]
We are hitting a crash inconsistently, never reproduced in dev but we are seeing it quite a bit in production.

On windows using 1.4.0 and libsodium we get the following stacktrace;
```
Application Specific Information:
Fatal Error: EXCEPTION_ILLEGAL_INSTRUCTION / 0x7ffd672c184d

Thread 5584 Crashed:
0   STServer.dll                    0x7ffd672c184d      sodium_misuse
1   STServer.dll                    0x7ffd672c1a91      crypto_aead_aes256gcm_beforenm
2   STServer.dll                    0x7ffd672a3fab      AES_GCM_CipherContext::InitCipher
3   STServer.dll                    0x7ffd67275231      SteamNetworkingSocketsLib::CSteamNetworkConnectionBase::FinishCryptoHandshake
4   STServer.dll                    0x7ffd672a93af      CUtlBuffer::PutOverflow
5   STServer.dll                    0x7ffd672a933f      CUtlBuffer::GetDelimitedCharInternal
6   STServer.dll                    0x7ffd67271c93      SteamNetworkingSocketsLib::CSteamNetworkConnectionBase::APIAcceptConnection
7   ntdll.dll                       0x7ffdb37a2bd8      TpPostTask
```

Sadly we cannot download the .dmp from our crash processor.

Any idea what could cause this issue?

**Comment by zpostfacto** [comment]
Not sure.  But you might see if 14e894d6736661d28bb786bc74e05c3d9a8a4449 changes anything.

**Comment by yamashi** [comment]
We managed to gather more info!

It happens on machines using Intel CPUs that have the AES-NI extension disabled in the BIOS. Once users go in the bios and enable it, the problem does not occur anymore.

The libsodium documentation states that this function requires AES-NI, there is no software fallback.

I suppose the only proper fix for this would be to use the OpenSSL/BCrypt crypto backends in our case.

Thanks for looking into it so quickly!

**Comment by zpostfacto** [comment]
Good to hear!  I think this change is good and would have made the problem more clear.  Not sure why it was written that way originally.

**Comment by darksylinc** [comment]
jedisct1/libsodium#234 is directly related to this issue.

[Apparently](https://github.com/jedisct1/libsodium/issues/234#issuecomment-139469707) the problem is that a SW-only implementation in constant time is (near?) impossible without HW support:

> "GCM is fundamentally unsuitable for software implementation."

I understand the rationale. As a gamedev-oriented library, we'd want to have fallback support.

But libsodium, as a security-oriented library, if it includes a SW fallback, it just adds a potential security vulnerability if an attacker manages to trick the library to downgrade & use the SW fallback instead of the HW one (or most likely, user-error is bound to happen from a reckless or clueless dev who disabled the HW version for some silly reason).

**Comment by zpostfacto** [comment]
There is a framework in place for more ciphers, and chacha20-poly1305 in particular.  Just requires a very small amount of plumbing.  If you want to add support, it should be straightforward.  This just isn't high enough on my priority list.

See #196.
