### ISSUE TITLE
Support building as a static library?

### ISSUE THREAD

**Issue by Elronnd** [ValveSoftware/GameNetworkingSockets#25]
There seem to be some flags in some headers that reference static linking, but no actual way exposed in the build files to build it that way?

**Comment by tycho** [comment]
Both Meson and CMake have static library targets:
https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/src/meson.build#L85
https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/src/CMakeLists.txt#L197

**Comment by Elronnd** [comment]
Oops...sorry, I somehow thought that the top-level CMakeLists.txt was the only cmake file (thought `add_subdirectory(src)` meant 'compile all the stuff in src') as I don't have much cmake experience.  Sorry...

**Comment by Elronnd** [comment]
Oops, I somehow thought that the top-level CMakeLists.txt was the only cmake file (thought add_subdirectory(src) meant 'compile all the stuff in src') as I don't have much cmake experience. Sorry...

**Comment by gregorypease280** [comment]
@tycho If possible could you give a quick example? I'm very new to cmake, I've built everything fine and am trying to link against GameNetworkingSockets_s.lib but I think I'm not passing in the correct cmake flags? Reason I say that is because I found some __declspec(dllexport)/dllexports in some of the generated header files.  I'm able to link properly with the dll but as soon as I try to use the static lib everything becomes unresolved. Any help would be super appreciated 🙏

**Comment by tycho** [comment]
@gregorypease280 Define STEAMDATAGRAMLIB_STATIC_LINK before including any GameNetworkingSockets headers, then link against GameNetworkingSockets_s.lib.

**Comment by tycho** [comment]
I've added STEAMDATAGRAMLIB_STATIC_LINK to the INTERFACE defines for GameNetworkingSockets_s, so when you tell a CMake project to link against it, it *should* define STEAMDATAGRAMLIB_STATIC_LINK automatically for you.

**Comment by gregorypease280** [comment]
@tycho thanks a ton!
