### ISSUE TITLE
Sockets polling on Windows

### ISSUE THREAD

**Issue by nxrighthere** [ValveSoftware/GameNetworkingSockets#49]
Fletch, consider `select()` instead of `WaitForMultipleObjects()` on Windows, it performs better (surprisingly) and reports multiple completed operations in a single call without any problems.

An ideal way to talk with the kernel would be IOCP, but this requires more changes to the code and the design itself is completely different (completion-oriented vs readiness-oriented/proactor vs reactor), but in terms of performance IOCP is the most performant and efficient approach than any other on Windows.

**Comment by fletcherdvalve** [comment]
If we identify a specific use case that is creating a lot of sockets and getting bad perf because of it, we could do this.  Note that socket != connection.  E.g. a server accepting a lot of connections might still only have a single socket.  Also if we switch to use select(), we'd need to do the equivalent of createsocketpair() to have one loopback socket used to signal to wake up the service thread.

Regarding IOCP, we use it on Steam, because many of our servers are Windows.  If we find an important user or use case where somebody is running a Windows server and there is evidence that this optimization is important, we could definitely consider it.  It was intentional to not use IOCP, because it is not cross platform.  (The server was linux for the initial use cases.)  I'm reluctant to use platform-specific optimizations that make the different platforms use fairly different architectures, without really good data that it will make an important use case better.

One of the main advantages of IOCP is avoiding copying the payload between application and kernel space.  We do a good job of avoiding extra copies right now when receiving messages (compared to a traditional API), but I have it on my list to add a Send call that accepts a message object, so that the caller could populate a buffer and hand it off to the API, avoiding copying the payload when sending as well.  (Just added issue #51 to track this.)

Also, with regard to polling in general, the most important use case we are not handling well right now is the event-driven server.  We only support the polling model right now.  We need a way for the app to wait efficiently and wake up as soon as a message is received or a state change occurs.  (Just added issue #52 to track this).

**Comment by nxrighthere** [comment]
> We need a way for the app to wait efficiently and wake up as soon as a message is received or a state change occurs. (Just added issue #52 to track this).

Yes, this is my main concern about this issue, https://github.com/ValveSoftware/GameNetworkingSockets/issues/52 will solve this indeed.

**Comment by nxrighthere** [comment]
> I think the callback interface is the most flexible, cross-platform interface, compared to say, a more direct "block here until something happens" API call. (But I do worry about people doing dumb stuff in the callback.)

Yes, and on practice, they are often brought there weird stuff, I encountered many problems around this.

It would be great if you can bring IOCP to this repository from Steam, especially if you are using Registered I/O there with it.

**Comment by fletcherdvalve** [comment]
Do you have any test batteries that measure the performance of the reliability layer in how well it deals with loss/latency?  E.g. how many packets/bytes does it end up sending, how many retries?  What is the average experienced latency at the application to receive a message (both reliable and unreliable)?  I am really curious how well our reliable layer is performing.  I know it works, and in theory it should be doing a good job of not resending more than necessary.  But I have not really made really solid comparisons.

Are your tests primarily concerned with CPU perf?  I would also be interested to see what test cases we do poorly on, if you have thrown this lib at those test cases.

**Comment by nxrighthere** [comment]
Also, I think it worth mention that [KCP](https://github.com/skywind3000/kcp/blob/master/README.en.md) retransmission strategies shows one of the best results in terms of latency but at the cost of bandwidth.

**Comment by fletcherdvalve** [comment]
Yes, I'm interested in the workload you are simulating.  With many threads accessing connections simultaneously, I would expect high contention and poor performance.  With a fewer number of threads accessing networking, I would expect it to be able to handle 70 clients at a reasonable message rate (~30hz).

**Comment by fletcherdvalve** [comment]
My expectation is that an ack-vector protocol should be able to perform better than any sliding window strategy.  But a lot can be done with tuning for particular network environments and workloads.  That's why I'm really interested in any existing benchmarks.

We're working on testing out using this protocol for in-home streaming on the steam link.  That is a fairly specific workload.  I'm interested if we can achieve close to the results that were obtained with the hand-coded retry methods, in a generic API.

**Comment by nxrighthere** [comment]
Drop me a message to my [email](mailto:nxrighthere), I'll send you back the program with in-depth explanations, and some thoughts tomorrow. 🍻

**Comment by nxrighthere** [comment]
I think we can close this since the mechanism to efficiently poll a set of connections was implemented.
