### ISSUE TITLE
Compiling with Clang and minbase_decls.h

### ISSUE THREAD

**Issue by Levendo** [ValveSoftware/GameNetworkingSockets#69]
Helloo,

I'm trying to compile the source code on Visual Studio 2017 with Android setup. I'm using CLang 5.0 as a compiler. "minbase_decls.h" has some definitions that gives error if there is no _MSC_VER and GNUC or COMPILER_PS3.  
 ```

#ifdef _MSC_VER
	// MSVC has the align at the start of the struct
	#define ALIGN8 DECL_ALIGN(8)
	#define ALIGN16 DECL_ALIGN(16)
	#define ALIGN32 DECL_ALIGN(32)
	#define ALIGN128 DECL_ALIGN(128)

	#define ALIGN8_POST
	#define ALIGN16_POST
	#define ALIGN32_POST
	#define ALIGN128_POST
#elif defined( GNUC ) || defined( COMPILER_PS3 )
	// gnuc has the align decoration at the end
	#define ALIGN4
	#define ALIGN8
	#define ALIGN16
	#define ALIGN32
	#define ALIGN128

	#define ALIGN4_POST DECL_ALIGN(4)
	#define ALIGN8_POST DECL_ALIGN(8)
	#define ALIGN16_POST DECL_ALIGN(16)
	#define ALIGN32_POST DECL_ALIGN(32)
	#define ALIGN128_POST DECL_ALIGN(128)
#else
	#error
#endif
```

Well, should i define GNUC for compiling with Clang or? Thanks.

**Comment by fletcherdvalve** [comment]
Sorry for the super late reply.

I'm actually not sure how we could have had issues with Clang before, since we supposedly have one of the continue integration tests build with clang?  (Although looking at that code, I don't know how it would have compiled with clang.)

E.g. https://travis-ci.org/ValveSoftware/GameNetworkingSockets/jobs/579985784

And I *think* I have compiled the code with Clang, perhaps as part of the Nintendo Switch port?  I remember specifically checking in clang fixes.

Regardless, all of that stuff has been deleted.  So you might see if the current master works?

**Comment by aiusepsi** [comment]
I think the issue is that `GNUC` isn't set as a predefined macro in either GCC or Clang (which both define `__GNUC__`) so the `GNUC` macro is only being defined by the build system upon detection either of GCC or Clang. So if you set things up to build a different way, or the build system detection gets broken somehow, the GNUC macro doesn't get defined as it should be, leading to breakage.

Might be worth just replacing all the instances of `GNUC` with `__GNUC__`. I can't personally think of any compelling reasons to keep `GNUC`.

**Comment by fletcherdvalve** [comment]
LoL, just noticed that line you linked to.

Yeah, that's dumb.  (I inherited that.)  I'll see if I can fix that.
