### ISSUE TITLE
ENet like channels?

### ISSUE THREAD

**Issue by moien007** [ValveSoftware/GameNetworkingSockets#95]
Does GNS provides [ENet](https://github.com/lsalzman/enet) like channels? This is useful for the game logic and user-voice packets distinction to take more advantage of bandwidth through single connection.

**Comment by helloer** [comment]
GNS does not offer such functionality, the following issue is related to your question: #68

**Comment by fletcherdvalve** [comment]
Yeah, don't close it, let's keep it open.  I think it is an interesting idea and I know there are use cases for it.  It's just not the most important project right now.

**Comment by fletcherdvalve** [comment]
Hello!  I have another partner who is interested in moving from Raknet, and they need a feature similar to this.

Can you describe in a bit more detail how the priority levels of the different channels behave?  Is one channel strictly higher priority than others?  Or is there a mechanism to prevent a high priority channel from totally starving a lower one?  Basically if there is data in multiple channels, how does ENet decide what to send?  Or maybe the more important question -- how do you think GameNetworkingSockets should decide what to send?

**Comment by moien007** [comment]
> Hello! I have another partner who is interested in moving from Raknet, and they need a feature similar to this.
> 
> Can you describe in a bit more detail how the priority levels of the different channels behave? Is one channel strictly higher priority than others? Or is there a mechanism to prevent a high priority channel from totally starving a lower one? Basically if there is data in multiple channels, how does ENet decide what to send? Or maybe the more important question -- how do you think GameNetworkingSockets should decide what to send?

I do maintain a wrapper for ENet but, unfortunately, I'm familiar with the inner workings of ENet.

**Comment by nxrighthere** [comment]
> Can you describe in a bit more detail how the priority levels of the different channels behave? Is one channel strictly higher priority than others? Or is there a mechanism to prevent a high priority channel from totally starving a lower one? Basically if there is data in multiple channels, how does ENet decide what to send? Or maybe the more important question -- 

ENet just decouples channels for reliable transmission to avoid head-of-line blocking when packets get lost, but prioritization is not a thing there.

If I remember correctly, SCTP has prioritization, but I don't know any technical details about it.

> how do you think GameNetworkingSockets should decide what to send?

To be honest, I believe this is something that should remain at high-level abstractions, so prioritization is implemented in accordance to game-specific mechanics/data/sync. This is directly related to https://github.com/ValveSoftware/GameNetworkingSockets/issues/44 and [eventual consistency](https://www.youtube.com/watch?t=36&v=dKa5DxRZ9I0&feature=youtu.be).

**Comment by nxrighthere** [comment]
> Can you describe in a bit more detail how the priority levels of the different channels behave? Is one channel strictly higher priority than others? Or is there a mechanism to prevent a high priority channel from totally starving a lower one? Basically if there is data in multiple channels, how does ENet decide what to send? Or maybe the more important question -- 

ENet just decouples channels for reliable transmission to avoid head-of-line blocking when packets get lost, but prioritization is not a thing there.

If I remember correctly, SCTP has prioritization, but I don't know any technical details about it.

> how do you think GameNetworkingSockets should decide what to send?

To be honest, I believe this is something that should remain at high-level abstractions, so prioritization is implemented in accordance to game-specific mechanics/data/sync. This is directly related to https://github.com/ValveSoftware/GameNetworkingSockets/issues/44 and [eventual consistency](https://www.youtube.com/watch?v=dKa5DxRZ9I0).

**Comment by fletcherdvalve** [comment]
>ENet just decouples channels for reliable transmission to avoid head-of-line blocking when packets get lost, but prioritization is not a thing there.

I don't understand what this means.  What is the functional difference between having multiple "channels", and opening up multiple connections between two peers?  When you have one connection, and the bandwidth estimator / packet pacer says it's time to send the next packet, and there is data pending in more than one channel, the code has to make a decision: Which channel's data should be sent?  One rule might be "always send the packet for the lowest numbered channel, if any", e.g. strict priority.  But there are other potential rules.

The main reason I'm asking is that Raknet's channels have a kind of "soft" priority.  If multiple channels are consistently full, then the channels will get an approximate percentage share of the connection's bandwidth, so that no channel gets totally starved.  By setting the percentages to an extremely large ratio like 9999:1, you effectively have strict priority.  But you could use other ratios, say 1:1, so that each channel is given an approximately equal share.

Right now I'm, inclined to set a relatively low limit on the number of channels (e.g. 4 or 8) and then allow you to set the priority weights for each channel, which represent the approximate proportion of the bandwidth the channel would consume in a steady state where all the channels were full.

The partner who has been asking about this specifically mentioned this aspect of Raknet's channels as being desirable.  My goal is to try to understand exactly what problems people asking for channels are trying to solve.

**Comment by nxrighthere** [comment]
> I don't understand what this means. What is the functional difference between having multiple "channels", and opening up multiple connections between two peers?

Connections in ENet represented as peers. A connection might have multiple channels that represent transmission streams. Reliable transmission in ENet based on a traditional sliding window similar to TCP with the same disadvantaged, channels just mitigates one of them.

I'm not familiar with RakNet channels, unfortunately.

**Comment by nxrighthere** [comment]
> I don't understand what this means. What is the functional difference between having multiple "channels", and opening up multiple connections between two peers?

Connections in ENet represented as peers. A connection might have multiple channels that represent transmission streams. Reliable transmission in ENet based on a traditional sliding window similar to TCP with the same disadvantages, channels just mitigates one of them.

I'm not familiar with RakNet channels, unfortunately.

**Comment by fletcherdvalve** [comment]
If I'm understanding you, it sounds like if I add the ability to assign weights to the given channels, you could get ENet-like behavior by setting all of the weights to be equal, which would give each channel an equal share of the bandwidth, and no channel starvation would occur, even if a very large reliable message was suddenly placed on one channel.

**Comment by nxrighthere** [comment]
It makes sense to add some bandwidth control/weight here, yes. But the primary goal is to avoid transmission stalls of reliable/ordered delivery.

A typical use-case:
1. Channel A used for chat messages.
2. Channel B used for game events.
3. A packet related to channel A was lost (transmission stalled), channel B operating independently.

**Comment by fletcherdvalve** [comment]
Do you think it is reasonable to impose a relatively tight limit on the number of channels?  Or perhaps there is no limit, but performance would suffer if the number of channels is excessively high.  For example, in some performance-critical code, there might be a loop to iterate over all the channels.  That's not a problem if the number of channels is 4, but if it's 65535, we have a problem.

**Comment by nxrighthere** [comment]
Yea, ENet supports up to 255 channels per connection. Something around 8 would be more than enough, I believe.

**Comment by fletcherdvalve** [comment]
Helloooooo from 2 years later!

@moien007 @nxrighthere I have a preliminary implementation of this feature.   If you have any feedback on the design of the interface, I'd be interested.

See: https://github.com/ValveSoftware/GameNetworkingSockets/blob/a835b8ce566ea02037642cea4eb717963a29793c/include/steam/isteamnetworkingsockets.h#L448

**Comment by ThusSpokeNomad** [comment]
hey @zpostfacto — coming back to this after a few years, I just wonder if connection lanes are implemented in such a way that they wouldn't block each other's reliable packets queue (aka head-of-line-blocking) — in other words, sending reliable packets on lane1 would not interfere with lane2's reliable packets and lane1 wouldn't block lane2's reliable delivery when it tries to resend packets (and vice-verca), they'd put resend efforts in their own "lanes", correct? based on the conversation so far, I think it was implied but I haven't fully read the source code yet and also wanted to keep this question as a note for the future if/when people dig deeper into this.

**Comment by ThusSpokeNomad** [comment]
Also, FWIW, I think this could be rephrased a bit differently (if my assumptions about separate "lanes" is correct):

> Head-of-line blocking control and bandwidth sharing of multiple message streams ("lanes") on the same connection. You can use strict priority values, softer [weight values](https://en.wikipedia.org/wiki/Weighted_fair_queueing) that control how bandwidth is shared, or some combination of the two methods. See [ISteamNetworkingSockets::ConfigureConnectionLanes](https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/include/steam/isteamnetworkingsockets.h).

A simple mention to the fact that different lanes would not head-on-line block each other (especially for reliable delivery) because they're running in different lanes would be a good clarification (again, if my assumption/expectation is correct here).

I'm happy to put up a PR repharesing this line slightly differently and/or even help contribute implementing the feature I'm after if it doesn't exist already.

Please LMK what you think! :)
